qc:
  database: pathogen_qc_grind
  host:     patp-db
  port:     3347
  user:     pathpipe_rw
  disable_emails: true


eukaryotes:
  database: pathogen_euk_track
  host:     patp-db
  port:     3347
  user:     pathpipe_ro

prokaryotes:
  database: pathogen_prok_track
  host:     patp-db
  port:     3347
  user:     pathpipe_ro

helminths:
  database: pathogen_helminth_track
  host:     patp-db
  port:     3347
  user:     pathpipe_ro

viruses:
  database: pathogen_virus_track
  host:     patp-db
  port:     3347
  user:     pathpipe_ro

pathogen_cgps_track:
  database: pathogen_cgps_track
  host:     patp-db
  port:     3347
  user:     pathpipe_ro
